name: Sample workflow

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: bcgov/action-builder-ghcr@v2.3.0
        with:
          package: backend
          tag: ${{ github.run_id }}
          tag_fallback: latest
          build_context: ./
          build_file: Dockerfile

  deploy:
    name: Deploy
    needs: [ build ]
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    environment: dev
    steps:
      - name: Deploys
        uses: bcgov/action-deployer-openshift@v4.0.0
        with:
          file: openshift.deploy.yml
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: true
          oc_version: "4.13"
          verification_path: /health
          parameters:
            -p BCREGISTRY_KEY=${{ secrets.BCREGISTRY_KEY }}
            -p BCREGISTRY_ACCOUNT=${{ secrets.BCREGISTRY_ACCOUNT }}
            -p ZONE=dev
            -p TAG=${{ github.run_id }}