name: Sample workflow

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: bcgov/action-builder-ghcr@v2.3.0
        with:
          package: test
          tag: test
          tag_fallback: latest
          build_context: ./
          build_file: Dockerfile